#!/bin/sh
red="\033[1;31m"
blue="\033[1;34mi"
reset="\033[0m"

printf "${blue}Running post-commit hook${reset}"

TITLE=$(git show -s --format=%s)
BODY=$(git show -s --format=%b)

# Rejects commit as function
reject() 
{
	git reset --soft HEAD~ > /dev/null 2>&1
	printf "${red}%s${reset}" "$1"
	exit 1
}

# Verify title length
if [ ${#TITLE} -gt 50 ]; then reject "Title is longer than 50 characters"; fi

# Verify body line length
for LINE in $BODY; do
	if [ ${#LINE} -gt 72 ]; then reject "Body has line longer than 72 characters"; fi
	break
done

printf "${blue}Commit looks fine${reset}\n"
if [ "$(git show -s --format=%an)" = "fprasx" ]; then printf "You're safe for now fprasx...\n"; fi
exit 0
